### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by kizzanaome**
@oxenprogrammer
@araaliFarooq
@faraqhan

### CODE REVIEW

**Comment by araaliFarooq** [comment]
@kizzanaome , could you resolve the conflicts in your pull request and also avoid inline css.

**Comment by oxenprogrammer** [comment]
Please do as farooq says. you will want to resolve it from your remote, it will allow you to compare the conflicting files.

**Comment by kizzanaome** [comment]
@araaliFarooq and @oxenprogrammer  thanks for the comment am gonna work on that...

**Review by hadijahkyampeire — APPROVED** [review]
LGTM

**Pull request merged**
